language: python

python:
    - 3.5.2

# install dependencies for development environment
install:
    - pip install -r requirements.txt
    - pip install coveralls

services:
  - postgresql

addons:
  postgresql: '10.3'

apt:
  packages:
    - postgresql-server-dev-10.3

sudo: true

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
    - py.test --cov

after_success:
    - coveralls

