language: python

python:
    - 3.5.2

# install dependencies for development environment
install:
    - pip install -r requirements.txt
    - pip install coveralls

services:
  - postgresql

addons:
  postgresql: '9.5'

apt:
  packages:
    - postgresql-server-dev-9.5

sudo: true

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
    - py.test --cov

after_success:
    - coveralls

