language: python

python:
    - 3.5.2

# install dependencies for development environment
install:
    - pip install -r requirements.txt

script:
    - pytest

virtualenv:
    system_site_packages: true
