language: python

python:
    - 3.5.2

# install dependencies for development environment
install:
    - pip install -r requirements.txt
    - pip install coveralls

services:
  - postgresql

addons:
  postgresql: '9.6'

apt:
  packages:
    - postgresql-server-dev-9.6

sudo: true

before_script:
  - sudo apt-get install postgresql-9.6-postgis-2.3 postgis -y -q
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis" -d symfony

script:
    - py.test --cov

after_success:
    - coveralls

