"""empty message

Revision ID: 8770690ae12e
Revises: 8652ee99d57e
Create Date: 2018-05-20 23:00:56.826184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8770690ae12e'
down_revision = '8652ee99d57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('book_author', sa.String(length=60), nullable=False))
    op.add_column('borrowed_books', sa.Column('book_description', sa.String(length=60), nullable=False))
    op.add_column('borrowed_books', sa.Column('book_title', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_books', 'book_title')
    op.drop_column('borrowed_books', 'book_description')
    op.drop_column('borrowed_books', 'book_author')
    # ### end Alembic commands ###
